import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'
import Layout from '../components/Layout'

export default function Home() {
  return (
    <div className='min-h-screen bg-zinc-900'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name='theme-color' content='#18181B' />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout className='bg-zinc-900 min-h-screen relative'>
      </Layout>

    </div>
  )
}
